/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * llquiz-backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { mutationInstance } from '../services/api';
export interface BodyCreateQuizApiV1QuizPost {
  name: string;
  file: Blob;
}

export interface BodyGradeQuizApiV1GradeQuizIdPost {
  file: Blob;
}

export interface GradeRankItem {
  rank: number;
  name: string;
  score: number;
  total: number;
  createdAt: string;
}

export interface GradeResultItem {
  number: number;
  selectedIndex: number | null;
  answerIndex: number;
  correct: boolean;
}

export interface GradeResponse {
  name: string;
  score: number;
  total: number;
  selectedIndexes: number[];
  result: GradeResultItem[];
}

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface ProblemPublic {
  question: string;
  choices: string[];
}

export interface QuizCreated {
  id: string;
}

export interface QuizDetail {
  id: string;
  name: string;
  count: number;
  createdAt: string;
  problems: ProblemPublic[];
}

export interface QuizListItem {
  id: string;
  name: string;
  count: number;
  createdAt: string;
}

export type HealthHealthGet200 = {[key: string]: string};

export type DbHealthHealthDbGet200 = {[key: string]: string};

export type CheckInviteInviteGet200 = {[key: string]: boolean};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary Health
 */
export const healthHealthGet = (

 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<HealthHealthGet200>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }




export const getHealthHealthGetQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getHealthHealthGetQueryOptions = <TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthHealthGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthHealthGet>>> = ({ signal }) => healthHealthGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthHealthGetQueryResult = NonNullable<Awaited<ReturnType<typeof healthHealthGet>>>
export type HealthHealthGetQueryError = unknown


export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthHealthGet>>,
          TError,
          Awaited<ReturnType<typeof healthHealthGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health
 */

export function useHealthHealthGet<TData = Awaited<ReturnType<typeof healthHealthGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthHealthGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthHealthGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Db Health
 */
export const dbHealthHealthDbGet = (

 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<DbHealthHealthDbGet200>(
      {url: `/health/db`, method: 'GET', signal
    },
      options);
    }




export const getDbHealthHealthDbGetQueryKey = () => {
    return [
    `/health/db`
    ] as const;
    }


export const getDbHealthHealthDbGetQueryOptions = <TData = Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDbHealthHealthDbGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dbHealthHealthDbGet>>> = ({ signal }) => dbHealthHealthDbGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DbHealthHealthDbGetQueryResult = NonNullable<Awaited<ReturnType<typeof dbHealthHealthDbGet>>>
export type DbHealthHealthDbGetQueryError = unknown


export function useDbHealthHealthDbGet<TData = Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dbHealthHealthDbGet>>,
          TError,
          Awaited<ReturnType<typeof dbHealthHealthDbGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDbHealthHealthDbGet<TData = Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dbHealthHealthDbGet>>,
          TError,
          Awaited<ReturnType<typeof dbHealthHealthDbGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDbHealthHealthDbGet<TData = Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Db Health
 */

export function useDbHealthHealthDbGet<TData = Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dbHealthHealthDbGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDbHealthHealthDbGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Check Invite
 */
export const checkInviteInviteGet = (

 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<CheckInviteInviteGet200>(
      {url: `/invite`, method: 'GET', signal
    },
      options);
    }




export const getCheckInviteInviteGetQueryKey = () => {
    return [
    `/invite`
    ] as const;
    }


export const getCheckInviteInviteGetQueryOptions = <TData = Awaited<ReturnType<typeof checkInviteInviteGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCheckInviteInviteGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof checkInviteInviteGet>>> = ({ signal }) => checkInviteInviteGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CheckInviteInviteGetQueryResult = NonNullable<Awaited<ReturnType<typeof checkInviteInviteGet>>>
export type CheckInviteInviteGetQueryError = unknown


export function useCheckInviteInviteGet<TData = Awaited<ReturnType<typeof checkInviteInviteGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkInviteInviteGet>>,
          TError,
          Awaited<ReturnType<typeof checkInviteInviteGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInviteInviteGet<TData = Awaited<ReturnType<typeof checkInviteInviteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof checkInviteInviteGet>>,
          TError,
          Awaited<ReturnType<typeof checkInviteInviteGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCheckInviteInviteGet<TData = Awaited<ReturnType<typeof checkInviteInviteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check Invite
 */

export function useCheckInviteInviteGet<TData = Awaited<ReturnType<typeof checkInviteInviteGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof checkInviteInviteGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCheckInviteInviteGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary List Quizzes
 */
export const listQuizzesApiV1QuizGet = (

 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<QuizListItem[]>(
      {url: `/api/v1/quiz`, method: 'GET', signal
    },
      options);
    }




export const getListQuizzesApiV1QuizGetQueryKey = () => {
    return [
    `/api/v1/quiz`
    ] as const;
    }


export const getListQuizzesApiV1QuizGetQueryOptions = <TData = Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQuizzesApiV1QuizGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>> = ({ signal }) => listQuizzesApiV1QuizGet(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQuizzesApiV1QuizGetQueryResult = NonNullable<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>>
export type ListQuizzesApiV1QuizGetQueryError = unknown


export function useListQuizzesApiV1QuizGet<TData = Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>,
          TError,
          Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuizzesApiV1QuizGet<TData = Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>,
          TError,
          Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQuizzesApiV1QuizGet<TData = Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Quizzes
 */

export function useListQuizzesApiV1QuizGet<TData = Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQuizzesApiV1QuizGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQuizzesApiV1QuizGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Create Quiz
 */
export const createQuizApiV1QuizPost = (
    bodyCreateQuizApiV1QuizPost: BodyCreateQuizApiV1QuizPost,
 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {

      const formData = new FormData();
formData.append(`name`, bodyCreateQuizApiV1QuizPost.name);
formData.append(`file`, bodyCreateQuizApiV1QuizPost.file);

      return mutationInstance<QuizCreated>(
      {url: `/api/v1/quiz`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getCreateQuizApiV1QuizPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuizApiV1QuizPost>>, TError,{data: BodyCreateQuizApiV1QuizPost}, TContext>, request?: SecondParameter<typeof mutationInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createQuizApiV1QuizPost>>, TError,{data: BodyCreateQuizApiV1QuizPost}, TContext> => {

const mutationKey = ['createQuizApiV1QuizPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createQuizApiV1QuizPost>>, {data: BodyCreateQuizApiV1QuizPost}> = (props) => {
          const {data} = props ?? {};

          return  createQuizApiV1QuizPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateQuizApiV1QuizPostMutationResult = NonNullable<Awaited<ReturnType<typeof createQuizApiV1QuizPost>>>
    export type CreateQuizApiV1QuizPostMutationBody = BodyCreateQuizApiV1QuizPost
    export type CreateQuizApiV1QuizPostMutationError = HTTPValidationError

    /**
 * @summary Create Quiz
 */
export const useCreateQuizApiV1QuizPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createQuizApiV1QuizPost>>, TError,{data: BodyCreateQuizApiV1QuizPost}, TContext>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createQuizApiV1QuizPost>>,
        TError,
        {data: BodyCreateQuizApiV1QuizPost},
        TContext
      > => {
      return useMutation(getCreateQuizApiV1QuizPostMutationOptions(options), queryClient);
    }

/**
 * @summary Get Quiz
 */
export const getQuizApiV1QuizQuizIdGet = (
    quizId: string,
 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<QuizDetail>(
      {url: `/api/v1/quiz/${quizId}`, method: 'GET', signal
    },
      options);
    }




export const getGetQuizApiV1QuizQuizIdGetQueryKey = (quizId: string,) => {
    return [
    `/api/v1/quiz/${quizId}`
    ] as const;
    }


export const getGetQuizApiV1QuizQuizIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError = HTTPValidationError>(quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuizApiV1QuizQuizIdGetQueryKey(quizId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>> = ({ signal }) => getQuizApiV1QuizQuizIdGet(quizId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: quizId !== null && quizId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuizApiV1QuizQuizIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>>
export type GetQuizApiV1QuizQuizIdGetQueryError = HTTPValidationError


export function useGetQuizApiV1QuizQuizIdGet<TData = Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizApiV1QuizQuizIdGet<TData = Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>,
          TError,
          Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuizApiV1QuizQuizIdGet<TData = Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Quiz
 */

export function useGetQuizApiV1QuizQuizIdGet<TData = Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuizApiV1QuizQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuizApiV1QuizQuizIdGetQueryOptions(quizId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







/**
 * @summary Grade Quiz
 */
export const gradeQuizApiV1GradeQuizIdPost = (
    quizId: string,
    bodyGradeQuizApiV1GradeQuizIdPost: BodyGradeQuizApiV1GradeQuizIdPost,
 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {

      const formData = new FormData();
formData.append(`file`, bodyGradeQuizApiV1GradeQuizIdPost.file);

      return mutationInstance<GradeResponse>(
      {url: `/api/v1/grade/${quizId}`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      options);
    }




export const getGradeQuizApiV1GradeQuizIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>, TError,{quizId: string;data: BodyGradeQuizApiV1GradeQuizIdPost}, TContext>, request?: SecondParameter<typeof mutationInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>, TError,{quizId: string;data: BodyGradeQuizApiV1GradeQuizIdPost}, TContext> => {

const mutationKey = ['gradeQuizApiV1GradeQuizIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>, {quizId: string;data: BodyGradeQuizApiV1GradeQuizIdPost}> = (props) => {
          const {quizId,data} = props ?? {};

          return  gradeQuizApiV1GradeQuizIdPost(quizId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GradeQuizApiV1GradeQuizIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>>
    export type GradeQuizApiV1GradeQuizIdPostMutationBody = BodyGradeQuizApiV1GradeQuizIdPost
    export type GradeQuizApiV1GradeQuizIdPostMutationError = HTTPValidationError

    /**
 * @summary Grade Quiz
 */
export const useGradeQuizApiV1GradeQuizIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>, TError,{quizId: string;data: BodyGradeQuizApiV1GradeQuizIdPost}, TContext>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof gradeQuizApiV1GradeQuizIdPost>>,
        TError,
        {quizId: string;data: BodyGradeQuizApiV1GradeQuizIdPost},
        TContext
      > => {
      return useMutation(getGradeQuizApiV1GradeQuizIdPostMutationOptions(options), queryClient);
    }

/**
 * @summary List Grades
 */
export const listGradesApiV1GradeQuizIdGet = (
    quizId: string,
 options?: SecondParameter<typeof mutationInstance>,signal?: AbortSignal
) => {


      return mutationInstance<GradeRankItem[]>(
      {url: `/api/v1/grade/${quizId}`, method: 'GET', signal
    },
      options);
    }




export const getListGradesApiV1GradeQuizIdGetQueryKey = (quizId: string,) => {
    return [
    `/api/v1/grade/${quizId}`
    ] as const;
    }


export const getListGradesApiV1GradeQuizIdGetQueryOptions = <TData = Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError = HTTPValidationError>(quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGradesApiV1GradeQuizIdGetQueryKey(quizId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>> = ({ signal }) => listGradesApiV1GradeQuizIdGet(quizId, requestOptions, signal);





   return  { queryKey, queryFn, enabled: quizId !== null && quizId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGradesApiV1GradeQuizIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>>
export type ListGradesApiV1GradeQuizIdGetQueryError = HTTPValidationError


export function useListGradesApiV1GradeQuizIdGet<TData = Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>,
          TError,
          Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGradesApiV1GradeQuizIdGet<TData = Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>,
          TError,
          Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGradesApiV1GradeQuizIdGet<TData = Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Grades
 */

export function useListGradesApiV1GradeQuizIdGet<TData = Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError = HTTPValidationError>(
 quizId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiV1GradeQuizIdGet>>, TError, TData>>, request?: SecondParameter<typeof mutationInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGradesApiV1GradeQuizIdGetQueryOptions(quizId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
